INFO     TestScripts.test_DataQuality:test_DataQuality.py:27 Test cases for supplier_data- file availability check has started ....
INFO     TestScripts.test_DataQuality:test_DataQuality.py:36 Test cases for supplier_data- zero byte size check has started ....
INFO     TestScripts.test_DataQuality:test_DataQuality.py:45 Test cases for supplier_data- duplicate row check has started ....
ERROR    CommonUtilities.utils:utils.py:94 error while reading the file unsupported file type passed TestData/supplier_data.json
ERROR    TestScripts.test_DataQuality:test_DataQuality.py:50  error occurred during test Supplier_data.json file has duplicate rows
assert None == True
 +  where None = check_duplicates_rows('TestData/supplier_data.json', 'json')
INFO     TestScripts.test_DataQuality:test_DataQuality.py:54 Test cases for supplier_data- null value heck has started ....
ERROR    CommonUtilities.utils:utils.py:94 error while reading the file unsupported file type passed TestData/supplier_data.json
ERROR    TestScripts.test_DataQuality:test_DataQuality.py:59  error occurred during test Supplier_data.json file has some null values
assert None == True
 +  where None = check_duplicates_rows('TestData/supplier_data.json', 'json')
